// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oscxtkqjkyllizhvhtxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zY3h0a3Fqa3lsbGl6aHZodHh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MDk2MjEsImV4cCI6MjA3MjM4NTYyMX0.oNrWeqw0pt1Am9gl5lZpni85Zcf14Cv9Q3G6gW5UWVc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});